[package]
name = "click"
version = "0.4.1"
description = "A command-line REPL for Kubernetes that integrates into existing cli workflows"
authors = ["Nick Lanham <nick@afternight.org>"]
homepage = "https://github.com/databricks/click/wiki"
repository = "https://github.com/databricks/click"
license = "Apache-2.0"
readme = "README.md"
keywords = ["kubernetes", "repl", "click", "cli"]
categories = ["command-line-interface", "command-line-utilities"]

[badges]
travis-ci = { repository = "databricks/click" }

[dependencies]
ansi_term = "0.9"
atomicwrites = "0.2.2"
base64 = "0.5"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.22"
ctrlc = "3.0"
der-parser = "0.3"
dirs = "1.0.4"
duct = "^0.12"
duct_sh = "^0.1"
humantime = "1.0"
hyper = "0.10"
hyper-sync-rustls = "0.3.0-rc.4"
lazy_static = "0.2"
os_pipe = "^0.5"
prettytable-rs = "^0.6"
regex = "0.2"
ring = "^0.13"
rustls = { version = "0.14", features = ["dangerous_configuration"] }
rustyline = "3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
tempdir = "^0.3"
term = "^0.4"
untrusted = "^0.6"
webpki = "^0.18"
